#!/bin/sh
#. "$(dirname "$0")/_/husky.sh"

# 🚀 Force correct nvm and Node.js
export NVM_DIR="$HOME/.nvm"
. "$NVM_DIR/nvm.sh"
nvm use default >/dev/null

echo "🔍 Running lint-staged..."
pnpm lint-staged || exit 1

#echo "🧪 Running tests for all workspaces..."
#pnpm test:all || exit 1